# Permalinks
permalink:        pretty

# Setup
url:              https://tvsijin.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Random Commits

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Personal Blog of Sijin Krishnan.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /hydejack/public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Sijin Krishnan'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        tvsijin
  github:         tvsijin

  # Setting a disqus username will enable the comment section
  disqus:         tvsijingithubio

  # This photo will be used in the about section
  photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Sijin Krishnan.

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
